// react-twitch-chat-socketio/client/src/components/ChatPausedAlert.tsx
import { GiPauseButton, ImArrowDown2 } from "react-icons/all";
import { useState } from "react";

const ChatPausedAlert = ({
  onClick: handleClick,
  className
}: {
  onClick: () => void,
  className?: string
}) => {
  const [ isHovered, setIsHovered ] = useState(false);

  const label = isHovered ? (
    <span className="inline-flex items-center">
      <ImArrowDown2 className="w-4 h-4" />
      See new messages
    </span>
  ) : (
    <span className="inline-flex items-center">
      <GiPauseButton className="w-4 h-4 mr-2" />
      Chat paused due to scroll
    </span>
  );

  return (
    <div
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      onClick={handleClick}
      className={`w-64 inline-flex justify-center px-4 py-2 rounded-lg bg-black/80 cursor-pointer ${className}`}>
      {label}
    </div>
  );
};

export default ChatPausedAlert;

// sveltekit-realtime-chat-socketio/client/src/routes/ChatPausedAlert.svelte
<script lang='ts'>
	import IoIosArrowDown from 'svelte-icons/io/IoIosArrowDown.svelte';
	import IoIosPause from 'svelte-icons/io/IoIosPause.svelte';
	import { createEventDispatcher } from 'svelte';

	const dispatch = createEventDispatcher();
	let isHovered = false;

	function handleClick() {
		dispatch('click');
	}
</script>

<div
	tabindex='0'
	on:mouseenter={() => isHovered = true}
	on:mouseleave={() => isHovered = false}
	on:click={handleClick}
	class='w-full max-w-[300px] inline-flex justify-center px-4 py-2 rounded-lg bg-black/60 cursor-pointer'>
	<div class='inline-flex items-center'>
		{#if isHovered}
			<div class='w-6 h-6 mr-4'>
				<IoIosArrowDown />
			</div>
			See new messages
		{:else}
			<div class='w-6 h-6 mr-4'>
				<IoIosPause />
			</div>
			Chat paused due to scroll
		{/if}
	</div>
</div>
